### PR TITLE
Add helpful debugging output with configuration

### PR DESCRIPTION
**Pull request by midas**
Hello and thank you for all your hard work on this library and the greater Elixir ecosystem.

While using Mox several of the developers in my company and myself have had a hard time tracking down un-mocked calls and ordering/reordering of calls when functionality changes. Additionally, sometimes the unhandled error's messages provide little to no clue of what is happening. Thus, it occurred to me that simply knowing exactly what is going on during a test's execution would help us through these situations.

I finally took a look at this problem today and the fix seemed rather simple, so I took a stab at it.

FYI, I chose to use a configuration instead of depending on Logger levels because most people run their test suites in debug mode, but do not desire constant debug output ruining the clean test suite views.

I did not write any tests for the functionality because it seemed ancillary.  However, I did ensure the current test suite is running clean with the changes. If you disagree with this point of view, please let me know your thoughts.

An example of output from the new functionalty follow:
```
MOCKED CALL Elixir.MyApp.MockService.call!/3 with args: [:BacklogQ1, :any, :next]
MOCKED CALL Elixir.MyApp.MockService.call!/3 with args: [:ProtocolAck1, :any, :ready]
UNMOCKED CALL Elixir.MyApp.MockService.call!/3 with args: [:RespQueue1, :any, {:all, 1}]
{:current_stacktrace,
 [{Process, :info, 2, [file: 'lib/process.ex', line: 640]},
  {Mox, :log_call, 5, [file: 'lib/mox.ex', line: 495]},
  {Mox, :__dispatch__, 4, [file: 'lib/mox.ex', line: 479]},
  {MyApp.Backend.Protocol.Foxtalk, :drain_resp_q, 1,
   [file: 'lib/backend/protocol/foxtalk.ex', line: 4]},
  {MyApp.Backend.Protocol.Foxtalk, :handle_info, 2,
   [file: 'lib/backend/protocol/foxtalk.ex', line: 106]},
  {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]},
  {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
```

I do believe this would be a valuable addition to Mox. Thanks again and take care!

Jason

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks for the issue and the feedback!

> Additionally, sometimes the unhandled error's messages provide little to no clue of what is happening.

Can you please provide examples about this? We should definitely improve the error messages because not everyone will know or remember to add flags to get logging output.

I would also prefer if this configuration happens per defmock instead of the application environment .

**Comment by midas** [comment]
Hi Jose.  Thanks for your time!

I will pull together some examples of error messages.

Regarding the configuration of the new feature being in `defmock` rather than the application environment, please explain further.  I am not following you on that one.

Jason

**Comment by josevalim** [comment]
> Regarding the configuration of the new feature being in defmock rather than the application environment, please explain further. I am not following you on that one.

Instead of:

```elixir
config :mox, log_mock_calls: true
```

I would prefer:

```elixir
Mox.defmock Foo, as: FooBar, log_mock_calls: true
```

But before you do those changes, let's see how we improve the error message, because things like `log_unmocked_calls` should not be necessary, assuming we have proper error messages. :)

**Comment by facto** [comment]
Thanks, Jose and Plataformatec, for this amazing mock library! It's the best one I've ever used. :)

I work with Jason and thought I would chime in since I've written a bunch of tests using mox mocks.

Here's an example of an error message I think can be improved.

When a mock function is called more times than expected, this is the error:

```
 ** (EXIT from #PID<0.1550.0>) an exception was raised:
   ** (Mox.UnexpectedCallError) expected MyApp.MockService.cast!/3 to be called once but it has been called 2 times in process #PID<0.1551.0>
       (mox) lib/mox.ex:444: Mox.__dispatch__/4
       (backend) lib/backend/protocol/foxtalk.ex:257: MyApp.Protocol.Foxtalk.process_frame/2
       (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
       (backend) lib/backend/protocol/foxtalk.ex:4: MyApp.Protocol.Foxtalk.handle_drain_resp_q/3
       (backend) lib/backend/protocol/foxtalk.ex:79: MyApp.Protocol.Foxtalk.handle_cast/2
       (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
       (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
       (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

In a scenario where there are many mock calls, it can be difficult to track down exactly where this call is in the call chain. It would be helpful to see at least the arguments that were passed.

But the arguments are only partially helpful when testing a scenario with many mock calls, sometimes several times to the same function. This is why we had the idea of logging out a 'trace' of expected and unexpected calls along with a stacktrace of each. This makes it a lot easier to get an idea of the entire call chain and visually verify each call.

I think configuration of logging mocked calls should at least be an option at the application level because we have dozens of mocks in one of our applications, and when we need a trace, we'd end up having to go through that entire list configuring only the ones we care about, or write a macro or something that adds the configuration to each line. To me, this is too much trouble. A simple toggle at the application level would be much more convenient and fit with the way we would use it-- when troubleshooting some non-obvious mock call that we missed in our testing.

Again, thanks for the library, and I look forward to continuing to use it.

**Comment by josevalim** [comment]
Beautiful. Let's start by adding the arguments to the error message? Then we can see evaluate how big of a difference it makes in those cases. Then rinse and repeat. :)

**Comment by josevalim** [comment]
To clarify, a PR that adds arguments to those messages would be very appreciated!

**Comment by midas** [comment]
Will do.  May take us a little while to get to it, but we will.  Thanks!

**Comment by josevalim** [comment]
Ping. :)

**Comment by josevalim** [comment]
I will go ahead and close this one but we are still glad to receive PRs and feedback on   how to improve error messages.

**Pull request closed without merging**
