### PR TITLE
Add ability to use mox without an explicit contract

### LINKED ISSUE #9: Should we support mocking modules without behaviour?
It's possible to verify function name and arity without behaviour callbacks.  I built support for this in double, but I'm curious if there are good reasons not to support this.  Does it break the "explicit contract" mantra?  

Related discussion: http://teamon.eu/2017/different-approach-to-elixir-mocks-doubles/#comment-3542001464

### PR DESCRIPTION
**Pull request by JoanZapata**
Fix #9 

I know you haven't really decided on what to do about that. We wanted this possibility in our project so I figured it would make sense to send you a PR and let you decide. 🙂

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @JoanZapata but truth be told we are more on the "no" side than on the "yes" side, as we believe this change can very easily lead to bad design between dependencies.

**Comment by JoanZapata** [comment]
Got it, thanks for your answer.

It makes us once again reconsider what we're doing and try to understand what could go wrong with it. Would you be okay to share some insights? I have of course read your [article](http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/) on mocks.

We wanted to use mock modules on our anti-corruption layers. Just to get a minimal example, currently that would look like this:

```elixir
defmodule Caller do
  @job_manager Application.get_env(:our_app, :job_manager)

  def foo do
    @job_manager.enqueue_at(date, module, params)  	
  end
end

defmodule JobManager do
  @doc ...
  @callback enqueue_at(...) :: ...
end

defmodule JobManager.Exq do
  @behaviour JobManager

  def enqueue_at(time, worker, args) do
    Exq.enqueue_at(Exq, @queue, time, worker, args)
  end
end
```

I see little added-value to the behaviour here, that's why I wanted to remove it, like this:

```elixir
defmodule Caller do
  @job_manager Application.get_env(:our_app, :job_manager)

  def foo do
    @job_manager.enqueue_at(date, module, params)  	
  end
end

defmodule JobManager do
  @doc ...
  @spec enqueue_at(...) :: ...
  def enqueue_at(time, worker, args) do
    Exq.enqueue_at(Exq, @queue, time, worker, args)
  end
end
```

* We're not "mocking" an external dependency or some code we don't control, `JobManager` is made specifically for `Caller`, acting as an ACL. 
* We can still use TDD using the module as a contract with no implementation.
* I'm not sure I understand how the behaviour was acting as "an explicit contract" anyway, since `@job_manager` was not explicitly typed with it.
* We can easily switch back to using behaviour if required. 

The only scenario I can imagine where behaviour is useful is if we package it with the `Caller` in a self-sufficient library with no external dependency. But in this case, how do I make an explicit link between `Caller` and the behaviour in this library?

I'm really just trying to see all the pros/cons of both approachs.

**Comment by josevalim** [comment]
I am not sure I can add anything beyond what is on the article. However, I would note that mock is not only about external dependencies. [The wikipedia page can provide more insights](https://en.wikipedia.org/wiki/Mock_object).

The main point is that mocks are meant to replace a dependency (internal or external) in your system and you cannot replace what has not been specified.

Alternatively, you can interpret it as: if you have mock, then there is always an interface, regardless if you explicitly define it or not. Mox forces you to define this interface, otherwise you would easily end-up with large contracts.

I would also like you to consider if you even want to mock it altogether. I am not sure what the capabilites behind Exq are, but you can also consider checking if the job was enqueued or always running enqueued jobs synchronously during tests without putting them on a queue. The choice depends on your system and if putting on the queue is an functional requirement or actually part of your specification.

**Comment by JoanZapata** [comment]
> I would also like you to consider if you even want to mock it altogether. 

Thanks for the suggestion. If we don't use a mock we would have to start a Redis database during our tests and make our expectations using either a Redis client or Exq (putting a job on the queue is a functional requirement). It would create a dependency between the business code and low-level technical details (exq), which we don't want.

> [...] always running enqueued jobs synchronously during tests without putting them on a queue.

Right, if we were to do that we would definitely need a behaviour to enforce a contract on both implementations.

---- 

I feel like what I'm missing with behaviours is the ability to explicitly declare them as such on the call site. 

Maybe something like this, that would check at compile time if the module retrieved from config is implementing the given behaviour:

```elixir
defmodule Caller do
  @job_manager Application.get_env(:our_app, :job_manager, as: JobManager)

  def foo do
    @job_manager.enqueue_at(date, module, params)  	
  end
end
```

Would that make sense? (I'm sorry I know I'm getting out of the scope of `mox`.)

**Comment by josevalim** [comment]
I am not sure I follow, you can say that a module follows a behaviour by saying `@behaviour Foo` when the module is defined.

**Comment by JoanZapata** [comment]
If it's not clear it probably means it's not a good idea. 😅

My point is that even when we use a behaviour, there is no explicit relationship between the **caller** and the behaviour. We rely *implicitely* on the proper module being set in the `dev`/ `prod` config file. It means a wrong config would crash at runtime.

I would like being able to do something like this...

```elixir
@job_manager Application.get_env(:our_app, :job_manager, as: JobManager)
```

... which would fail at compile time if we set a wrong module in the config. But most of all it would make it clear that we expect an implementation of this behaviour in `@job_manager`. Currently we don't have this information.

I think it makes behaviours more relevant, but of course that's just my opinion.

Is it clearer?

**Comment by JoanZapata** [comment]
Err, right, I'm quite new to Elixir and it's still a hard pill to swallow. 💊

I'll get use to it eventually! Thanks for your help.

**Pull request closed without merging**
